import { pgTable, text, serial, timestamp, real, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const groceryTable = pgTable("grocery_items", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  quantity: real("quantity").notNull(),
  unit: text("unit").notNull(),
  category: text("category"),
  isPurchased: boolean("is_purchased").notNull().default(false),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  reason: text("reason"),
  addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertGrocerySchema = createInsertSchema(groceryTable).omit({ id: true, addedAt: true });
export type InsertGrocery = z.infer<typeof insertGrocerySchema>;
export type GroceryItem = typeof groceryTable.$inferSelect;
